# Generated by Django 5.0.4 on 2024-04-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('INR', 'Indian Rupee'), ('EUR', 'Euro'), ('GBP', 'British Pound Sterling'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('NZD', 'New Zealand Dollar'), ('CNY', 'Chinese Yuan Renminbi'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('ZAR', 'South African Rand'), ('RUB', 'Russian Ruble'), ('KRW', 'South Korean Won'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
