# Generated by Django 5.0.4 on 2024-04-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_must_be',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ATM_DEBIT_TRANSACTION', 'ATM and Debit Card Transaction'), ('RTGS', 'Real-Time Gross Settlement (RTGS)'), ('IBFT', 'Inter Bank Funds Transfers (IBFT)'), ('DEPOSIT_BANK_CHECK', 'Deposit Bank Check'), ('PAY_ORDER', 'Pay Order'), ('DEMAND_DRAFT', 'Demand Draft'), ('CASH_DEPOSIT', 'Cash Deposit'), ('CASH_WITHDRAWAL', 'Cash Withdrawal')], max_length=50, verbose_name='Transaction_Type'),
        ),
    ]
